trigger:
  branches:
    include:
      - master
      - develop

pool:
  vmImage: ubuntu-latest

variables:
  user: menziess
  email: stefan_schenk@hotmail.com
  repo: barbeque
  python.version: "3.8"

stages:
  - stage: "Vlees Converter"
    jobs:
      - job: Convert
        steps:
          - task: UsePythonVersion@0
            displayName: "Use Python $(python.version)"
            inputs:
              versionSpec: "$(python.version)"

          - script: pip install pipenv && pipenv install -d --system --deploy --ignore-pipfile
            workingDirectory: tools/vlees-converter
            displayName: "Install dependencies"

          - script: pip install -e .
            workingDirectory: tools/vlees-converter
            displayName: "Install vlees-converter"

          - script: to-templates
            displayName: "Convert csv to templates"

  - stage: Website
    jobs:
      - job: Pubish
        steps:
          - checkout: self
            submodules: true

          - script: |
              make install-hugo
            displayName: Install hugo extended

          - script: |
              git submodule add https://github.com/$(user)/$(repo).git public
              rm -rf public/*
            displayName: Add submodule to push generated site to

          - script: hugo
            displayName: Build static site

          - script: |
              cd public
              echo Changed directory to $(pwd)
              git checkout master
              git add --all
              git -c user.name=$(user) -c user.email=$(email) commit -m "commit $(date +"%Y_%m_%d_%I_%M_%p")"
              git push -f https://$(token):x-oauth-basic@github.com/$(user)/$(repo).git $(Build.SourceBranchName)
            displayName: Push generated site to github.io
