
trigger:
  branches:
    include:
      - master
      - develop

pool:
  vmImage: ubuntu-latest

variables:
  user: menziess
  email: stefan_schenk@hotmail.com
  repo: barbeque
  products_path: content/products
  python.version: "3.8"

stages:
  - stage: Converter
    jobs:
      - job: Build
        steps:
          - task: UsePythonVersion@0
            displayName: "Use Python $(python.version)"
            inputs:
              versionSpec: "$(python.version)"

          - script: pip install pipenv && pipenv install -d --system --deploy --ignore-pipfile
            workingDirectory: tools/vlees-converter
            displayName: "Install dependencies"

          - script: make build
            workingDirectory: tools/vlees-converter
            displayName: "Create Wheel"

          - task: CopyFiles@2
            displayName: Copy dist files
            inputs:
              sourceFolder: tools/vlees-converter/dist/
              contents: vlees_converter*.whl
              targetFolder: $(Build.ArtifactStagingDirectory)
              flattenFolders: true

          - task: PublishBuildArtifacts@1
            displayName: PublishArtifact
            inputs:
              pathtoPublish: $(Build.ArtifactStagingDirectory)
              ArtifactName: vlees_converter.whl

  - stage: Website
    dependsOn: Converter
    jobs:
      - job: Publish
        steps:
          - checkout: self
            submodules: true

          - task: UsePythonVersion@0
            displayName: "Use Python $(python.version)"
            inputs:
              versionSpec: "$(python.version)"

          - download: current
            artifact: vlees_converter.whl

          - script: pip install $(Pipeline.Workspace)/vlees_converter.whl/*.whl
            displayName: Install vlees-converter

          - script: |
              contents="$(jq '.installed.client_secret = env.CLIENT_SECRET' credentials.json)" && \
              echo "${contents}" > credentials.json
            displayName: Set google client secret
            env:
              CLIENT_SECRET: $(client_secret)

          - script: |
              rm -rf $(products_path)
              # download_csv 1EDZQHGoad_XQabpskXeT7Q5A0n55L4Gisz1v8a5O1Vo assortiment/data.csv
              to-templates assortiment/data.csv $(products_path)
              ls $(products_path)
            displayName: Convert csv to products

          - script: |
              make install-hugo
            displayName: Install hugo extended

          - script: |
              git submodule add https://github.com/$(user)/$(repo).git public
              rm -rf public/*
            displayName: Add submodule to push generated site to

          - script: hugo
            displayName: Build static site

          - script: |
              cd public
              echo Changed directory to $(pwd)
              git checkout $(Build.SourceBranchName) 2>/dev/null || git checkout -b $(Build.SourceBranchName)
              git add --all
              git -c user.name=$(user) -c user.email=$(email) commit -m "commit $(date +"%Y_%m_%d_%I_%M_%p")"
              git push -f https://$(token):x-oauth-basic@github.com/$(user)/$(repo).git $(Build.SourceBranchName)
            displayName: Push generated site to github.io
