name: Build and Deploy

on:
  workflow_dispatch:
  #push:
    #branches:
      #- master
      #- develop

jobs:
  converter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install pipenv && pipenv install -d --system --deploy --ignore-pipfile
        working-directory: tools/vlees-converter

      - name: Create Wheel
        run: make build
        working-directory: tools/vlees-converter

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: vlees_converter
          path: tools/vlees-converter/dist/vlees_converter*.whl

  website:
    needs: converter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Download Built Artifact
        uses: actions/download-artifact@v3
        with:
          name: vlees_converter

      - name: Install vlees-converter
        run: pip install vlees_converter.whl/*.whl

      - name: Set Google Client Secret
        run: |
          contents="$(jq '.installed.client_secret = env.CLIENT_SECRET' credentials.json)" && \
          echo "${contents}" > credentials.json
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

      - name: Convert CSV to Products
        run: |
          rm -rf content/products
          to-templates assortiment/data.csv content/products
          ls content/products

      - name: Install Hugo
        run: make install-hugo

      - name: Add Submodule and Clean Public Directory
        run: |
          git submodule add https://github.com/${{ secrets.USER }}/barbeque.git public
          rm -rf public/*

      - name: Build Static Site
        run: hugo

      - name: Push Generated Site to GitHub
        run: |
          cd public
          git checkout $(git rev-parse --abbrev-ref HEAD) 2>/dev/null || git checkout -b $(git rev-parse --abbrev-ref HEAD)
          git add --all
          git -c user.name=${{ secrets.USER }} -c user.email=${{ secrets.EMAIL }} commit -m "commit $(date +"%Y_%m_%d_%I_%M_%p")"
          git push -f https://${{ secrets.TOKEN }}:x-oauth-basic@github.com/${{ secrets.USER }}/barbeque.git $(git rev-parse --abbrev-ref HEAD)
        env:
          USER: ${{ secrets.USER }}
          EMAIL: ${{ secrets.EMAIL }}
          TOKEN: ${{ secrets.GH_PAT }}
