name: Deploy to Another Repo and Server

on:
  push:
    branches:
      - main  # Adjust if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Clone Target Repository
        run: |
          git clone https://github.com/YOUR_USERNAME/TARGET_REPO.git target-repo
          cd target-repo
          git checkout main  # Adjust branch if needed

      - name: Copy New Code
        run: |
          cp -r YOUR_FILES target-repo/  # Adjust files to copy
          cd target-repo
          git add .
          git commit -m "Automated update from main repo"
          git push https://YOUR_GH_PAT@github.com/YOUR_USERNAME/TARGET_REPO.git main

        env:
          YOUR_GH_PAT: ${{ secrets.GH_PAT }}

      - name: Deploy to Server via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}  # Use SSH keys if possible
          source: "target-repo/"
          target: "/var/www/html/"  # Adjust your server path
